### ISSUE TITLE
Huge memory usage in Linux

### ISSUE THREAD

**Issue by ricwtk** [sadovnychyi/autocomplete-python#233]
I have installed this module in Ubuntu 16.04 and Mac OSX El Capitan. The one in OSX gives me no problem but in Ubuntu 16.04 when I open a python file and start typing, a python process is spawned and the memory usage of the process keep increasing until it saturates all the RAM. This away immediately when I disable the module.

**Comment by sadovnychyi** [comment]
Is it with same project or different ones? Can you enable logging in package settings and look what's going on?

**Comment by chxxpeng** [comment]
Actually I've meet the same problem in Windows 8.1 Python 2.7.12.
It happens for all my different projects.
When I enable the package autocomplete-python, 20mins later, the process python.exe will use huge memory and CPU usage. When disable the package, all work well.

**Comment by sadovnychyi** [comment]
As long as I cannot reproduce it I'm afraid I cannot do anything.

**Comment by ivasonn** [comment]
@sadovnychyi try to disable "Show Descriptions"

**Comment by sadovnychyi** [comment]
@ivasonn wow, that's useful info, thanks.

I can confirm that with enabled "Show Descriptions" I have ~50mb memory usage after typing `import ` and I'm getting list of all my packages in less than a second, while with disabled "Show Descriptions" it takes tens of seconds and uses 1.3gb of ram.

**Comment by sadovnychyi** [comment]
Fixed the huge difference in time while loading list of modules after you type `import` keyword.

```bash
time python lib/completion.py '{"id":"0","prefix":" ","lookup":"completions","source":"import ","line":0,"column":7,"config":{"showDescriptions":false}}'
real	0m1.291s
user	0m1.037s
sys	0m0.172s

time python lib/completion.py '{"id":"0","prefix":" ","lookup":"completions","source":"import ","line":0,"column":7,"config":{"showDescriptions":true}}'
real	0m1.078s
user	0m0.919s
sys	0m0.147s
```

It took tens of seconds before fix to get a completion with descriptions turned off.

It's still going to take a while for huge modules like tensorflow though. With both config variations.

```bash
time python lib/completion.py '{"id":"0","prefix":" ","lookup":"completions","source":"import tensorflow\ntensorflow.","line":1,"column":11,"config":{"showDescriptions":false}}'
real	0m30.721s
user	0m27.276s
sys	0m1.437s

time python lib/completion.py '{"id":"0","prefix":" ","lookup":"completions","source":"import tensorflow\ntensorflow.","line":1,"column":11,"config":{"showDescriptions":true}}'
real	0m23.345s
user	0m21.873s
sys	0m0.776s
```

**Comment by sadovnychyi** [comment]
Please try it with 1.8.10. Should be better now if you have "Show Descriptions" turned off.

**Comment by ivasonn** [comment]
it's ok

**Comment by neutralinsomniac** [comment]
I still have this issue in version 1.8.11 with Show Descriptions turned off. I am also trying to autocomplete wx-related things.

**Comment by sadovnychyi** [comment]
Can confirm, installed `wx` using `brew install wxpython`, then:
```bash
python lib/completion.py '{"id":"0","prefix":" ","lookup":"completions","source":"import wx; wx.","line":0,"column":14,"config":{"showDescriptions":false}}'
```

Takes minutes to load and requires a lot of CPU time.

Reason – the library has a *lot* of stuff in the root. Not sure about the best way to fix this. The `autocomplete-plus` does not support lazy loading of additional attributes as your scroll through completions – so it's seems like everything should be done within python script, and it should limit the maximum number of completions it returns to autocomplete-plus. But this won't allow us to filter completions using `fuzzaldrin-plus` which is pretty good.

**Comment by sadovnychyi** [comment]
https://github.com/davidhalter/jedi/issues/805

**Comment by lunchboxmg** [comment]
I have been experiencing the same problem on Windows.  Anytime I tried to use autocomplete on an object that was subclassed from a wx object, within seconds, all my ram would be gone.  But, i realized I had two versions of wxpython installed (2.8 and 3.0).  Uninstalled the 2.8 version and have no problems now.

**Comment by Idalvar** [comment]
I've been having a similar issue.

I use ubuntu 16.04 and the autocomplete process sometimes ramps up to 100% CPU load and starts eating up all of my RAM at a pretty steep rate.

I've pinned it down to when I'm working with the gnuradio module which is probably quite big.

**Comment by devuberoi** [comment]
I've been experiencing this too, my Macbook's fans started to make noise. When I checked Activity Monitor, a python process was consuming almost 100% CPU.

output of : ps aux | grep python

USER               PID  **%CPU** %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
myuser        55563 **100.0**  0.0  2484232    852   ??  R     5:31PM 183:59.62 /Users/myuser/Projects/env/bin/python /Users/myuser/.atom/packages/autocomplete-python/lib/completion.py

does it have anything to do with python virtual environments?

**Comment by sadovnychyi** [comment]
See related Jedi issue above. It's likely because of a huge package you use.

**Comment by andrasikladi** [comment]
I love this package with Atom but I'm having the same issue on a different scale:

Importing the Python API from a DCC application called Houdini (https://sidefx.com, free to download for testing) that has about 40MB of code and 250k lines (some SWIG generated, mostly hand written by the look) in Python 2.7 results in a Python process with 30GB+ memory use and takes about 5 minutes to complete. Afterwards (given enough memory) it's not too bad.

Interestingly the same setup is fine with numpy (160k+ lines) or even with wx-3.0-gtk2 (40MB, 320k lines) or similar large libraries. They're taxing but gets nowhere near this bad.

I've tried to switch off all the other packages and tried the "Show descriptions" hack but no real difference. Nothing much in the Developer log either.

Python version: 2.7.5 Houdini version (also tried 2.7.12 system and even a clean virtualenv)
Autocomplete-Python package version: 1.8.63
Atom version: 1.16.0 x64
OS: Linux Mint MATE 18.1 (4.4.0-77-generic)
HW: 128GB/48cores

So I guess it comes down to the previously reported Jedi issue but is there a way to massage the library into a more consumable shape? What are the main culprits? Just the number of definitions, docstrings or code too?

**Comment by sadovnychyi** [comment]
@andrasikladi unfortunately right now there's no way to limit the Jedi in number of completions to returns, see that issue. Until it's fixed, there's nothing I can do about it.

*Maybe* you could modify the Regex to trigger Autocompletions setting to ignore completions from that specific module, but I'm not sure that it will work. (e.g. there's no context available, only current word)

**Comment by mkotlyar** [comment]
I have the same issue when working on a project that uses `wx` package.

**Comment by grantstephens** [comment]
I am having the same issue- not using jedi (unless this installs it in the background) though. Ubuntu 17.04 and autocomplete-python 1.10.2. Atom 1.19.3.

**Comment by bitinerant** [comment]
The first time I tried this, it hard-froze my Ubuntu 16.04 laptop.  Subsequent tries worked, but used almost all of my 8GB of RAM until I disabled "Show Descriptions".

Maybe, until this is fixed, "Show Descriptions" should be disabled by default.

To reproduce:
  * install the package, keep default options
  * copy code (yes, it uses wx) from http://upgrayd.blogspot.de/2010/11/python-mandelbrot.html
  * near the top of the file, start a new line and type:  self.
  * watch your RAM usage rapidly climb

**Comment by anxuae** [comment]
Do you have any news about this topic?

Even with "Show Descriptions" disabled, the issue is still present.
The only way to solve it, it's to disable _autocomplete-python_ for projects which use _wx_.

**Comment by sadovnychyi** [comment]
Cannot do anything until https://github.com/davidhalter/jedi/issues/805 is fixed. Even if you run pure Jedi on `wx` completion it will eat your memory and CPU.

It's also currently not possible to use `triggerCompletionRegex` setting to ignore some package completions, since the prefix provided by Atom excludes everything after a dot. E.g. for `wx.` the prefix is just a dot. So you can either completely disable completions on dot by removing the dot match from that regexp, OR we could try to modify the prefix on the fly so you could be more flexible on what you can ignore with that regexp.

The only solution right now is to disable autocomplete after a dot character by using this regexp:

`([ (]|[a-zA-Z_][a-zA-Z0-9_]*)`

Put it into `Regex To Trigger Autoocmpletions` setting. This should limit the number of completions you get. (hopefully! didn't try it by myself)

**Comment by elliott-beach** [comment]
The Visual Studio Code extension for Python, which also uses Jedi, dealt with this by killing the competition process if it uses more than a set limit, defaulting to 1 GB (https://github.com/Microsoft/vscode-python/pull/744).
